### ISSUE TITLE
Unclear/unspecified copyrights

### ISSUE THREAD

**Issue by andrewshadura** [stsundermann/webkitgtk-sharp#8]
Could you please add proper copyright/license statements somewhere? As it is now, it's very ambiguous and unclear (is it Andreia Gaita? Stephan Sundermann? someone else? is the license LGPLv3 or "LGPLv3 or later"?). Basically, nothing explicitly states the code is actually covered by LGPL and it's not just the license text attached to the source code.

Please fix this :)

**Comment by stsundermann** [comment]
What exactly do you need? The code is autogenerated by the gtk# generator and thus has no copyright notice in it.
The license is LGPLv3. I took over the work from Andreia during GSoC and improved it, so we are both copyright holders I guess.

**Comment by andrewshadura** [comment]
I guess adding a clear copyright statement to the README.md (the more or less standard ‘[this program is free software: you can redistribute it…](http://www.gnu.org/licenses/gpl-howto.en.html)’) copyright notice would be fine). Also, please specify if this is LGPLv3 or LGPLv3 or later.

**Comment by shana** [comment]
@stsundermann What do you think of moving this to MIT/X11?

**Comment by shana** [comment]
We could certainly use a little more standardization in the license/readme/contributing files here. I'll whip up a PR for that :smile:

**Comment by stsundermann** [comment]
I'm fine with the MIT/X11 license as well.

**Comment by andrewshadura** [comment]
So, would you please add the necessary copyright/license statements? (and for [soup-sharp](/stsundermann/soup-sharp) too, please)

**Comment by stsundermann** [comment]
Is this alright? 
https://github.com/stsundermann/webkitgtk-sharp/commit/f98a0db9437d14c14715a4af1c8ffd049665cb33

**Comment by andrewshadura** [comment]
Sure, thanks!

**Comment by andrewshadura** [comment]
Oh, and maybe add the authors.

**Comment by andrewshadura** [comment]
Wow, great, thanks! :) [appindicator-sharp](/stsundermann/appindicator-sharp) too, please :)
